### ISSUE TITLE
Add imview task

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#172]
Would be nice to have this for a diagnostic plotter - at least for the calibrator fields.

**Comment by radiosky-abhik** [comment]
Yes, we want to plot the redundant baselines Amplitude in a Time Vs Freq plane. I think Ben found out 'imview' can be used for this purpose. Somehow it will be more nice if people can make a movie of all the redundant baselines in a Time Vs Freq plane, not sure whether this can be managed by some tasks? Thanks.
