### ISSUE TITLE
Implement LOFAR software images into STIMELA for LOFAR reduction pipeline

### ISSUE THREAD

**Issue by JulienNGirard** [ratt-ru/Stimela#19]
Motivation for it:
- 3C147 LOFAR Data (calibrator snapshot with international baseline from proprietary data from LC6_008 (PI: Daniel Santos-Cosa, CI: Julien Girard) available on /vault/girard
- Angry radioastronomers desperately wanting an easy way to implement pipelines for LOFAR Data in production mode.
- Propose an alternate way to PREFACTOR which is a pain and generate a LOT of output logs.

Requirements:
I) One LOFAR base image
II) Specific LOFAR image derived from the base image:
- GSM.py (MonetDB service for generating sky models at low frequencies from NVSS/VLSS/PKS)
- NDPPP (data station/time/freq flagging / Data averaging / Clock-TEC separation / Demixing / DIE gain cal) 
- LOSOTO (Lofar Solution Tool)
- BBS (just to be consistent for LOFAR users because studies have shown that NDPPP Gain cal is faster and better than BBS.)
- LOFAR imagers (LWimager/AWimager1&2/DDFacet, again for consistency)
- Source finders (pyBDSM/PYSE/Sourcery...)
- ...

Questions: 
- how to deal with various parsets and inputs (one kind for NDPPP, one kind for BBS, one kind for the imagers) ?
- how to deal with multiples MS in a single run (necessary for Clock-TEC separation in the spectral domain) ?

**Comment by SpheMakh** [comment]
@JulienNGirard how is it going?

**Comment by JulienNGirard** [comment]
Hey. I have some trouble dealing with all the modes of NDPPP. I am trying to validate my script on data I know to be sure.

**Comment by SpheMakh** [comment]
Hey @JulienNGirard , how is this going. Let me know if I can help

**Comment by SpheMakh** [comment]
Hehe, I doubt this will happen before Jesus comes back ;)
