### ISSUE TITLE
stimela does not accept valid patterns for both ddfacet and cubical

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#375]
the Data-MS and Modellist parameters of ddfacet and cubical are not parsed correctly. These are not necessarily of type "list:file", but rather strings that may contain colons e.g. "Data-MS": "G330.1GC.ms//D*//F0:6" to specify a list of DDIDs and FIELDS that cannot be specified otherwise in the case of DDFacet, or @o-smirnov's cool new cubical syntactic sugar where you can do MODEL+-some.lsm.html@de:some.lsm.html@de

I've made fixes for this in a branch.

**Comment by bennahugo** [comment]
I think stimela needs to be smarter about how it does io specifiers. maybe do a regex match to :input$, :msdir$ and :output$ instead of just splitting by colon. At the moment it is necessary to set them to string parameters and fill the path manually using os.env.

**Comment by SpheMakh** [comment]
All these fancy, non-standard ways of specifying parameters are very sweet but catering for them in a consistent way is a bit of a pain. But I'm always open to ideas. Can you make a regex implementation and we can see how that goes.

**Comment by o-smirnov** [comment]
Let's not blame non-standardness here. :) This is a philosophical issue -- if stimela's mission is to wrap every possible software package, then you can't be declaring a character such as the colon or the slash off-limits, and then blaming the package for employing those characters in its interface... 

I think what's needed rather is a consistent quoting/escape-character mechanism so that any such weirness can be catered for.

**Comment by SpheMakh** [comment]
> I think what's needed rather is a consistent quoting/escape-character mechanism so that any such weirness can be catered for. 

This is impossible if no characters are off-limits, or at the very least the set and meaning of possible **special** characters is fixed. You simply cannot have consitency without standardising some things.

**Comment by o-smirnov** [comment]
It can't be impossible in principle. Hence, quoting and escaping. Every programming language deals with this one way or another, else we couldn't embed arbitrary strings into a program....

**Comment by SpheMakh** [comment]
I have should've used the word "intractable" instead of "impossible". In any case, the reality is that we will need to deal with these special cases as they come.

**Comment by SpheMakh** [comment]
@bennahugo for `io` specification I think the cleanest way is to have an option `set_io` in the `Recipe.add()` function, and set non-standard `io` options there. Something like this should do

```
recipe.add("cab/cubical", ..., set_io={
    "inputs.model" : "output", 
    "inputs.beam_pattern" : "msdir"
}
```

**Comment by SpheMakh** [comment]
For cubical model specification, we can use regex in the cubical `run.py` and keep extending the expression(s) as fancier things emerge.

**Comment by o-smirnov** [comment]
> In any case, the reality is that we will need to deal with these special cases as they come.

Surely there must be a systemic solution to string quoting? Where do you parse the parameters?

**Comment by SpheMakh** [comment]
The problem is not reading in special characters in string. The issue is that stimela has a standard way to accept inputs from the user, and depending on the type the parameters have to be validated before being parsed to the package. Now, this becomes a bit difficult if the parameter is an expression that operates on files. There are also `io` issues since the filesystem is not the same on the host and the container where the package is executed (solution two comments above should fix the `io` issue). 

A solution is to define an "expression" type which can be accompanied by a regex expression (or a set) and custom validation functions. The regex and validation functions may have to be different for each special case.

**Comment by bennahugo** [comment]
I have a simpler solution that should work, but it will change the way stimela works underneath the hood. The alternative is to run in a fourth directory (not the output directory) and symlink all files in input msdir and output to that directory upon starting the job. This will work around the need to parse patterns and the current very clumsy overrides specifier, and more resemble a standard workflow. The catch is that the ':<dir>' directive will be obsoleted.

**Comment by bennahugo** [comment]
A differential filelist is kept and those output files are moved back to the output folder

**Comment by SpheMakh** [comment]
> This will work around the need to parse patterns and the current very clumsy overrides, specifier 

How will it get around the need to parse to patterns? Also symlinks get a bit tricky when working on shared filesystems which will be the case when we start using batch systems.

**Comment by SpheMakh** [comment]
The `io` flow is not the problem here. The way that Docker mounts files makes it easier to mount files where you need to be at runtime, there is no need for symlinks. The issue is correctly interpreting and validating expressions that involve files. I don't see a universal way of doing this, which is why I think the "regex + validation function" I describe above is a neat solution.

**Comment by bennahugo** [comment]
if all the files live in the same folder to start off with you do not need to parse and amend patterns.  By shared file systems do you mean shared folders with multiple stimela instances running across nodes? That seems a bit dangerous to start off with. Otherwise I don't see why a shared network mountpoint will make any difference. You mount directories input, msdir and output into a container. Whether they are network mounts or not it makes no difference what so ever. The runtime will make a temporary directory somewhere (it could even be inside output). A differential list of what is in input, msdir and output is made using glob. That list is then symlinked inside the temp. The run is completed and whatever is new is moved one step up to output. That way no pattern matching is involved. The cubical modellist pattern (for instance) may need multiple override directives as it currently stands. Users may want to do something like "MODEL+-input/lsm.html+-output/lsm2.html@de:output/lsm2.html". This way all files live together and there is no need to care for these highly unusual special directories.

**Comment by bennahugo** [comment]
the alternative is to make available some properties to be filled at runtime, so that patterns can be build with that say 'MODEL+-$(os.path.join(stimela.INPUT,mylsm.html))+-$(os.path.join(stimela.OUTPUT,mysecondlsm.html)@dE:$(os.path.join(stimela.OUTPUT,mysecondlsm.html)@dE in true bash style. Whatever is in $() is eval'd and executed, unless \$ is escaped

**Comment by bennahugo** [comment]
This way you can even link output from previous steps like $("a" if "something appear in log" in stimela.RECIPE.stepname.log else "b")

**Comment by bennahugo** [comment]
if you don't like the $() syntax we can work around it by doing something like the stimela.dismissable special object and call it stimela.pyeval or something

**Comment by SpheMakh** [comment]
@bennahugo you have fixed this right?

**Comment by SpheMakh** [comment]
resolved

**Comment by bennahugo** [comment]
No it was never merged in - I think you reverted it. 
--Data-MS in DDFacet is not a file for instance, so you cannot treat it as IO -- or at least you should not check it

**Comment by bennahugo** [comment]
I'm also testing a change locally to build cubical on top of the new ddfacet (release pending)

I need to cater for the following model type specification
COLUMN_NAME+-model.lsm@de:model.lsm@tag
or
COLUMN_NAME+-model.DicoModel@regionsfile.reg:model.DicoModel@regionsfile.reg

I think in this case (as with the special inputs into mstransform for example) the relative path inside the container needs to be specified. We need a new special replacement type (as we have with the dismissive type) to check for patterns inside a string and replace it with the relative directories

I suggest something like
pathfinder("COLUMN_NAME+-${output}model.DicoModel@${output}regionsfile.reg:${output}model.DicoModel@${output}regionsfile.reg")

**Comment by bennahugo** [comment]
\$ \{ and \} will be escape characters supported internally for cases where patterns may contain $ already, like beams.

**Comment by bennahugo** [comment]
I would then also deprecate your ```:output``` syntax with a warning of removal. This syntax I think is more instructive

**Comment by SpheMakh** [comment]
I marked it resolved, and not fixed because mixing types in this way is bad practice because inputs cannot be validated.

**Comment by SpheMakh** [comment]
There are just too many ways in which this can go wrong. Especially since we are migrating to the CWL standard

**Comment by SpheMakh** [comment]
> I would then also deprecate your :output syntax with a warning of removal. This syntax I think is more instructive 

No. DDfacet and Cubical, as python packages, should follow standard python practices. The best we can do is write wrappers in the src/run.py that make them compatible to the stimela standard.

**Comment by o-smirnov** [comment]
What do you mean by standard Python practices in this case? Command-line arguments are what they are, some need rich syntax, some don't.

I would suggest allowing "{variable_name}" substitutions, if we're going to be Pythonic.

**Comment by bennahugo** [comment]
Yes I would like to see the PEP standard that says patterns cannot be specified as commandline arguments....

**Comment by bennahugo** [comment]
Any case there are a lot of packages that take multiple types as input parameters... casa being a prime example, so this will need to be wrapped if cwl does not allow multiple input types

**Comment by SpheMakh** [comment]
> I would suggest allowing "{variable_name}" substitutions, if we're going to be Pythonic. 

This only works if the variable is defined. Which is exactly what I'm proposing. I have no problems using patterns. The issue is patterns which files/directories which have not been defined because it makes it unnecessarily difficult to anticipate and handle exceptions and do parameter validation. Any self-respecting workflow should validate parameters. Here is the solution I have been proposing for years now,

Instead of having this ninja business
```
COLUMN_NAME+-model.DicoModel@regionsfile.reg:model.DicoModel@regionsfile.reg
```
why something like this

```
binary --model-lsms lsm1 lsm2 lsm2 --model-columns DATA MODEL_DATA --regions reg1 reg2 --model-expr "col[0]+-lsm[0]@region[1]:lsm[2]@region[1]" 
```

Where you separate the setting of parameters from the expression. It is longer yes, but it is more robust, allows parameters to be validated and makes it easier to deal with exceptions.

**Comment by SpheMakh** [comment]
And just to be clear, cubical/DDFacet can parse options however they like. But, as is the with CASA, MeqTrees, SoFiA and other tasks stimela has wrappers to make the tools conform to a standard. Stimela does not guarantee the same API as the underlying application, although we do try to be as accommodating as reasonably possible.

**Comment by SpheMakh** [comment]
> Any case there are a lot of packages that take multiple types as input parameters... casa being a prime example, so this will need to be wrapped if cwl does not allow multiple input types 

Yeah, that is exactly what I've been saying all this time. We put CubiCal and DDFacet into the looney bin with CASA and write wrappers for them in run.py (or the CWL equivalent)

**Comment by SpheMakh** [comment]
We've even done it already for CWL


https://github.com/ratt-ru/Stimela/blob/4d0f8a13576edf1d5f636b22b653e0b0336e42c2/stimela/cargo/cab/cubical.cwl#L39-L65

https://github.com/ratt-ru/Stimela/blob/4d0f8a13576edf1d5f636b22b653e0b0336e42c2/stimela/cargo/cab/cubical.cwl#L2280-L2292

**Comment by bennahugo** [comment]
This does not work for region file tags or dicomodels:

> We've even done it already for CWL
> 
> https://github.com/ratt-ru/Stimela/blob/4d0f8a13576edf1d5f636b22b653e0b0336e42c2/stimela/cargo/cab/cubical.cwl#L39-L65
> 
> https://github.com/ratt-ru/Stimela/blob/4d0f8a13576edf1d5f636b22b653e0b0336e42c2/stimela/cargo/cab/cubical.cwl#L2280-L2292

**Comment by bennahugo** [comment]
As discussed I'm pushing a path pattern formatter that will format the paths to be relative inside a container using @o-smirnov's syntax, along with a series of unit tests.

**Comment by bennahugo** [comment]
''' 
    Wrapper for path variables that need further expansion
    to include base directories
    expect:
        pattern: of the format (({})?[\s\S-[{}]]*)*, {} indicate placeholders where
                 paths are to be inserted. \{ and \} escapes these groups
        *args: of special types pathfinder.input, pathfinder.output and
               pathfinder.msdir. Will attempt to replace placeholders in order
               of *args specification
    Example:
        {
            'model': pathfinder("MODEL_DATA:{}/mod2.lsm:{}/mod3.DicoModel", "output", "input")
        }
        This will create placeholders for output and input on the second and third files
        respectively.
    '''

**Comment by SpheMakh** [comment]
> This does not work for region file tags or dicomodels: 

Does Cubical accept region files or dicomodels?

**Comment by bennahugo** [comment]
> > This does not work for region file tags or dicomodels:
> 
> Does Cubical accept region files or dicomodels?

Yes it does

**Comment by SpheMakh** [comment]
Cool. We'll extend the cab definition
