### ISSUE TITLE
Singularity does not support shm-size setting

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#394]
Just a note on this. It looks like singularity is bound to what ever shm is set in cgroups limits, unlike docker which use escalated privileges  to change this kernel parameter.  So existing scripts may run out of memory at the 50% system memory limit that is imposed on most systems

**Comment by bennahugo** [comment]
@KshitijT @SpheMakh please note this impacts all the packages that use shared memory in the back.

**Comment by KshitijT** [comment]
Fun.

**Comment by SpheMakh** [comment]
Nothing we can do about this
