### ISSUE TITLE
Keeping up with Software: Spruce up parameters

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#412]
There are a bunch of parameters missing from Cubical (e.g. -sel-diag, see PR #410 ) and a bunch of parameters which are now obsolete (e.g. montblanc-feed-type, removed a year ago). I guess we need to polish up the parameter file to keep up with the latest Cubical (whatever the version actually being used by Stimela, I mean) ?

**Comment by bennahugo** [comment]
Same goes for ddfacet. A slew of parameters have been added and a slew have
been removed.

It is probably easier to burn parameters.json to the ground and start
afresh.
