### ISSUE TITLE
Support software requiring running X on ${DISPLAY} using XVFB

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/Stimela#427]
This is a stimela issue, solution provided by @bennahugo, but I don't understand.
https://github.com/ska-sa/meerkathi/issues/522#issue-464124188

**Comment by o-smirnov** [comment]
Arguably, this is an rfinder issue really: https://github.com/Fil8/RFInder/issues/30

However, this is a common error with other packages (importing matplotlib without taking care about the backend), so perhaps it would be good to make Stimela robust against this, by adopting @bennahugo's suggestion of running with an Xvfb (inside the conrtainer) to absorb any unintended X11 calls.

**Comment by SpheMakh** [comment]
Fixed
