### ISSUE TITLE
Running DDFacet with uDocker

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#451]
Logging an apparent error:

1. I used a stimela script (latest master branch) to image a MS with DDFacet.
2. The MS did not have a CORRECTED_DATA column, I was trying to (mistakenly) image it.
3. While using uDocker, the script just ran without any error messages, of course without producing any output products.
4. While using Singularity, the script immediately crashed with the message:
```
RuntimeError: TableProxy::getColumnSliceVH: column CORRECTED_DATA does not exist

```

So it seems like uDocker version does not produce any error message.

**Comment by bennahugo** [comment]
It just means the containers are likely not checking error codes correctly. I hope this can actually be checked with udocker. Its time to bring back the explict failure checking tests @SpheMakh

**Comment by SpheMakh** [comment]
Fixed
