### ISSUE TITLE
Enable invert-uvw switch in Crystalball?

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#464]
Following this discussion on Crystalball: https://github.com/paoloserra/crystalball/issues/19, I guess we should enable the ``` invert-uvw``` parameter in ```crystalball```?

**Comment by paoloserra** [comment]
That parameter was replaced with `--exp-sign-convention` in https://github.com/paoloserra/crystalball/commit/83f8bbc8229254e70ef16729a4740744d0b42c16

Whoever takes care of https://github.com/SpheMakh/Stimela/issues/476 should include all crystalball 0.2.2 parameters in Stimela -- it's very few anyway.

**Comment by SpheMakh** [comment]
Fixed
