### ISSUE TITLE
Docker image not found after updating on singularity

### ISSUE THREAD

**Issue by ianjarog** [ratt-ru/Stimela#503]
After updating, the pipeline cannot find this image stimela_codex-africanus_1.2.5.img, it looks for it but 
the one in the singularityimage folder is stimela_codex-africanus_1.2.3.img, as a temporary fix, I just renamed the  stimela_codex-africanus_1.2.3.img to  stimela_codex-africanus_1.2.5.img

**Comment by SpheMakh** [comment]
You need to pull the new codex-africanus image
```
stimela pull -s -cb crystalball 
```
