### ISSUE TITLE
AWImager

### ISSUE THREAD

**Issue by radiosky-abhik** [ratt-ru/Stimela#51]
Hi Speh,
               Can you please add AWImager in Stimela..Thanks.

Cheers,
 Abhik

**Comment by JulienNGirard** [comment]
Hello, I can't answer for Sphe, but I can speak for the upcoming LOFAR software as new cabs for Stimela.
NDPPP, BBS and AWimager/LWimager(which is already present as a cab) are going to be implemented soon in Stimela.
As most of these packages are already shipped as debian packages on the radioastro/Kern repository, this should be straightforward.
One has to pay attention, to install part of the LOFAR libraries that implements the LOFAR stations beams (at least HBA and also LBA if I'm not wrong).

Cheers

Julien

**Comment by radiosky-abhik** [comment]
Thanks Julien.

--  Abhik

<abhik@phy.iitkgp.ernet.in>
