### ISSUE TITLE
Singularity containers run in CWD ${HOME} instead of output

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#518]
Although home is defined as output inside the run shell script the CWD is never changed to output.
Certain packages dump temp in the CWD which needs to be captured in output. Prime example are the relatively chunky BBC gain terms in cubical which exceeds the storage capacity of non-root built singularity images.

**Comment by o-smirnov** [comment]
I don't know if it's a prime example of anything. The gains are dumped to
whatever the output filename is set to. I think it's more of an example of
the output filename not set correctly!

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by o-smirnov** [comment]
Or I should say cubical in Stimela is clearly misconfigured in this instance (the out-of-the-box setting for ``--bbc-save-to`` is a pattern resulting in a file in the output directory -- I don't know how or why the pattern got changed to ``"file"``) and this needs to be fixed [here](https://github.com/ratt-ru/Stimela/blob/master/stimela/cargo/cab/cubical/parameters.json#L361). Maybe just set to ``null`` like the other ``save-to`` defaults. But shouldn't the default behaviour be "save something sensibly named in the output directory"?

But I agree that it would be more robust to chdir to output anyway as a general default. Many software authors assume CWD is a safe place to write stuff to.
