### ISSUE TITLE
Add new version of Eidos to Stimela

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/Stimela#526]
The latest version of Eidos provides a ~~better estimation~~ better headers of the primary beam (as per @bennahugo ). Can we update the version in Stimela master version to match? 
If this has been done already somewhere please close this issue. It would be great if this could go in before the next release.

**Comment by bennahugo** [comment]
Its not a better estimation of the beam it simply fixes the WCS headers of the beam cubes

**Comment by KshitijT** [comment]
> Its not a better estimation of the beam it simply fixes the WCS headers of the beam cubes

Thanks, description amended.

**Comment by gigjozsa** [comment]
Of course, but we need to get it done once, see MeerKATHI issue [#837](https://github.com/ska-sa/meerkathi/issues/837). Please oh masters of Stimela?

**Comment by SpheMakh** [comment]
Fixed
