### ISSUE TITLE
Release Stimela

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/Stimela#528]
Could you please release [2c5fea1](https://github.com/ratt-ru/Stimela/commit/2c5fea1aaf237117266fcf3f7342348d15ff3260) or get MeerKATHI into sync with Stimela otherwise? [2c5fea1](https://github.com/ratt-ru/Stimela/commit/2c5fea1aaf237117266fcf3f7342348d15ff3260) is the last Stimela that works with MeerKATHI (at least using Docker, Singularity giving problems).

**Comment by KshitijT** [comment]
Please see #526 .

**Comment by gigjozsa** [comment]
@SpheMakh @bennahugo @Athanaseus @KshitijT could anyone of you issue a Stimela release **of the current master** now, at this moment (whenever you wake up)? See [MeerKATHI#833](https://github.com/ska-sa/meerkathi/issues/833#issuecomment-601008942).

**Comment by gigjozsa** [comment]
Now, please? I succeeded with a MeerKATHI testrun for both Singularity and Docker. The reason for former failures has been found.

**Comment by gigjozsa** [comment]
@SpheMakh @bennahugo sorry, my request above was premature. Just generated an error using stiimela plotms in MeerKATHI:
[MeerKATHI#797](https://github.com/ska-sa/meerkathi/issues/797)

**Comment by gigjozsa** [comment]
@SpheMakh Stimela commit a346b985fb875aac10e7933725abac5e21e62f4e (current master) successfully ran with MeerKATHI. Could you release Stimela with that commit (current master)?

**Comment by gigjozsa** [comment]
@SpheMakh we'd require a release for the next MeerKATHI master including @o-smirnov 's logging pull request. Could you? Thank you!

**Comment by gigjozsa** [comment]
Updating this request because of #558 , which CARACal is affected by.

**Comment by gigjozsa** [comment]
Could we release Stimela? See https://github.com/ska-sa/caracal/issues/987

**Comment by gigjozsa** [comment]
Could we release Stimela? See https://github.com/ska-sa/caracal/issues/1028

**Comment by gigjozsa** [comment]
See https://github.com/ska-sa/caracal/pull/1033

**Comment by gigjozsa** [comment]
We'd request the current master to be released.

**Comment by gigjozsa** [comment]
See https://github.com/ska-sa/caracal/issues/1041

**Comment by SpheMakh** [comment]
Hopefullly, for good this time.

**Comment by gigjozsa** [comment]
... to make caracal usable using STIMELA_PULLFOLDER, see https://github.com/caracal-pipeline/caracal/issues/1150
