### ISSUE TITLE
Residual python 3 non-utf8 encoded string logging errors

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#530]
As per: @IanHeywood reports this dreaded error again on the CHPC cluster:

--- Logging error ---
Traceback (most recent call last):
 File "logging/__init__.py", line 982, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 452:
ordinal not in range(128)

Running it inside a Stimela container, so maybe the issue belongs there, but reopening it here just so it doesn't get lost.

**Comment by IanHeywood** [comment]
I should note that Tricolour runs to completion, it's just the first thing that happens is a unicode error, so PBS writes the rest of the log output to the error file not the log file. Not critical but not pretty.

Possibly related to @bennahugo's comment in https://github.com/ska-sa/tricolour/issues/42, I'm not using stimela itself, just stealing the containers from the docker page.

**Comment by SpheMakh** [comment]
should be fixed in tricolour
