### ISSUE TITLE
execution failed while running casa_flagdata mode='clip'

### ISSUE THREAD

**Issue by francescaLoi** [ratt-ru/Stimela#536]
I tried to create a basic reduction recipe where I added casa_listobs and casa_flagdata. If I use flagdata with the parameter mode='manual' I don't have any troubles but with mode='clip' it doesn't work. 
I installed stimela with the following standard commands:

> virtualenv -p python3 testvenv
> source testvenv/bin/activate
> rm ~/.stimela/*
> pip install stimela
> stimela pull -d
> stimela build

on ubuntu 18.04 system with no errors. 

The script that I am trying to run is:
```
# import stimela package
import stimela
import os
# Recipe I/O configuration
INPUT = "input"  # This folder must exist
OUTPUT = "output"
MSDIR = "msdir"
PREFIX = "stimela-example"  # Prefix for output images
try:
    SINGULARTITY_IMAGE_DIR = os.environ["STIMELA_SINGULARTITY_IMAGE_DIR"]
except KeyError:
    SINGULARTITY_IMAGE_DIR = None
# MS name
MS = 'ngc612.ms.0'
# Use the NVSS skymodel. This is natively available
LSM = "nvss1deg.lsm.html"
# Start stimela Recipe instance
pol_cal = stimela.Recipe("pol_cal",     # Recipe name
                          ms_dir=MSDIR,
                          #singularity_image_dir=SINGULARTITY_IMAGE_DIR,
                          log_dir=os.path.join(OUTPUT, "logs"),
                          )
pol_cal.JOB_TYPE = "docker"
pol_cal.add("cab/casa_listobs",
            "listobs",
             {
                 "vis": MS,
                 "verbose": True,
             },
             input=INPUT, output=OUTPUT,
             label="List obs")
pol_cal.add("cab/casa_flagdata",
           "flagdata3",
            {
                "vis": MS,
                "mode": 'clip',
                "clipminmax": [0,6],
                "correlation": 'XX,YY',
            },
            input=INPUT, output=OUTPUT,
            label="Flag clip")
pol_cal.run()
```
And when I run it, after the listobs output:
![err](https://user-images.githubusercontent.com/58785332/77753132-3007a980-7029-11ea-822a-5d20e9868c48.png)

**Comment by francescaLoi** [comment]
Same problem with mode='tfcrop'.

**Comment by KshitijT** [comment]
clipminmax is a float list?
Try with:              `  "clipminmax": [0.0,6.0],` .

**Comment by SpheMakh** [comment]
@francescaLoi I suspect that the **correlation** selection is erroneous. Could you try re-run without setting it

**Comment by francescaLoi** [comment]
Still the same error even after implementing both of your suggestions.

**Comment by SpheMakh** [comment]
There is a warning about **CORRECTED_DATA** not existing, the default in stimela is corrected. 
https://github.com/ratt-ru/Stimela/blob/cc41d99030357486c3a8acbef766463e56a4a71d/stimela/cargo/cab/casa_flagdata/parameters.json#L132-L135

Could you explicitly specify `datacolumn` as **data**

**Comment by francescaLoi** [comment]
It worked! Thank you!!!

**Comment by paoloserra** [comment]
@SpheMakh we can keep this issue closed but there is something I don't understand.

If I run the same command in CASA with datacolumn="CORRECTED" I get  the same WARN and SEVERE messages, but CASA does not crash. So why is Stimela crashing?

And another thing: why is  Stimela crashing with a message that calls `/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py`? I thought Stimela only used  stuff from the virtual environment where it was installed.

**Comment by SpheMakh** [comment]
> If I run the same command in CASA with datacolumn="CORRECTED" I get the same WARN and SEVERE messages, but CASA does not crash. So why is Stimela crashing?

CASA tasks do crash, which is a cardinal sin in programming (Think pineapple on a pizza). To be more specific, it does not throw exceptions when a task fails, it just prints out a message to stdout. To make matters worse, SEVERE messages can mean that the task failed, and sometimes not. This makes it difficult to have CASA in a pipeline, (at least if you care about when your pipeline fails). This is why I wrote this *crashing CASA* wrapper, [crasa](https://github.com/SpheMakh/crasa), which goes through the log files looking failures and SEVERE messages and then raises exceptions. In crasa, you can specify whether a task should crash or continue if a SEVERE message is raised

```
class CasaTask(object):
    def __init__(self, task, casa="casa", 
                 crash_on_severe=True, logfile=None, 
                 ignore_leap_second_severe=True,
                 **kwargs):
```

It is set to `True` by default. 




> And another thing: why is Stimela crashing with a message that calls /usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py? I thought Stimela only used stuff from the virtual environment where it was installed.

This the python environment inside the docker container which is different from the host.

**Comment by paoloserra** [comment]
OK, makes sense about CASA (not) crashing, thanks.

About the location of Crasa -- please enlighten my poor soul: how could I have understood that that's the python environment inside the docker container? 

I now see that /usr/local/lib/python2.7/dist-packages/ has no Crasa on my machine indeed -- but,  had I noticed before your reply, I would have been even more confused!

Anyway, time for some pizza with pineapple now! 🍕

**Comment by SpheMakh** [comment]
> About the location of Crasa -- please enlighten my poor soul: how could I have understood that that's the python environment inside the docker container?

If you are using stimela, then any path that does not have stimela in the directory hierarchy is most likely in the container.

**Comment by paoloserra** [comment]
okay, thanks for the help
