### ISSUE TITLE
Running Stimela jobs on Ilifu (IDIA)

### ISSUE THREAD

**Issue by nkululekoq** [ratt-ru/Stimela#547]
Hi 

I need your help with setting up my Stimela jobs. What I would or trying to do is run a number of Stimela simulations (64 at the moment) in parallel or on different nodes. However, what I have found is that I only get a few of them to run simultaneously even when there are nodes that are free. They block and run serially thereafter. What I have done for now is to restart some of the blocked jobs and specify the nodes to run on. This works but am going to scale-up my simulations and would not be practical to manually check which jobs are blacked and restart them. 

I run my simulations in a virtual environment where I have installed Stimela. I would also like to have a Stimela container that has all the software I need for my simulations in-order not to use virtual environments for this in the long run. 

This is my sbatch script
_#!/bin/bash

#SBATCH --job-name=mk1$j'job'
#SBATCH --cpus-per-task=1
#SBATCH --mem=8GB
#SBATCH --output=mk1-job-%j-stdout.log
#SBATCH --error=mk1-job-%j-stderr.log
#SBATCH --nodes=5
#SBATCH --mail-user=nqwabe@ska.ac.za
#SBATCH --mail-type=END,FAIL

exec stimela run /users/nkululekoq/scripts/sim_mk1_minusant$SLURM_ARRAY_TASK_ID.py_

I then run the script passing a batch array like: 
_sbatch --array=0-63%5 mk1_batch.sh_

I would appreciate your advice on how to resolve this. 

Thank you.

**Comment by SpheMakh** [comment]
Sho razo, kuhamba kahle ngala?
