### ISSUE TITLE
"outputs wrangler" for dealing with unruly cabs

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela#548]
As proposed earlier -- since you have no control over the payload's quirks, foibles and silly messages, how about we add formal wrangling mechanism to give cab developers a chance to tame unruly payloads.

Something along the lines of, let the cab definition include an optional list of "wrangling rules". Each rule is a (*match*, *replace*, *action*) tuple.

*Match* is a regex that is matched against each output message to see if the rule applies.

*Replace* allows the content of the message to be modified. If not None, you call ``message = re.sub(match, replace, message)`` to modify the message.

*Actions* allows other things to happen with the message. Useful actions I can think of:

* SUPPRESS: suppress the message entirely

* an ``int``: log the message at this level (rather than the default logging.INFO). Useful for escalating certain output to warnings or errors.

* DECLARE_SUCCESS: mark the payload as having successfully finished, even if the exit code is non-0

* DECLARE_FAILURE: mark the payload as failed, even if the exit code is 0.

* a callable: call it as ``callable(job, match)``. This is the generic power tool basically.

* a list: treat it as a list of actions and apply them in sequence

**Comment by SpheMakh** [comment]
Done
