### ISSUE TITLE
should the default task logfile level be DEBUG? 

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela#552]
Is this wise? https://github.com/ratt-ru/Stimela/blob/master/stimela/recipe.py#L109

I would argue for INFO. Stimela is meant to be mature and stable, so its housekeeping debug output ought to only be useful when a developer is bug-hunting in Stimela itself, which is rare.

Things going wrong inside a cab, on the other hand, are routine, and the users always look at logs to diagnose them. Stimela's own debug output then only gets in the way.

**Comment by bennahugo** [comment]
@o-smirnov isn't interferometry and  radio science in general always just in -O0 + debug symbols mode?

**Comment by o-smirnov** [comment]
Hehe, true. But if you think about it, that's all the more reason to keep the default cab logs more about interferometry, and less about dirty container laundry.

I know @paoloserra believes in giving the user plenty of rope... I just think the rope should be velvet! (And Rhodes purple...)

**Comment by paoloserra** [comment]
I'm with you on this one @o-smirnov . Indeed, I've never said it has to be a rough rope.

**Comment by o-smirnov** [comment]
Hmm, I thought I changed it in some PR or other, but it's still dumping DEBUG stuff out into the main log...
