### ISSUE TITLE
ddfacet singularity image broken

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#556]
This used to work in docker (and passed the test) so singularity is again playing games. I have removed the singularity cache and cleared .local to no avail

**Comment by bennahugo** [comment]
```
## Traceback (most recent call last):
##   File "/usr/local/bin/DDF.py", line 26, in <module>
##     from DDFacet.compatibility import range
##   File "/usr/local/lib/python3.6/dist-packages/DDFacet/__init__.py", line 23, in <module>
##     __version__ = pkg_resources.require("DDFacet")[0].version
##   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 901, in require
##     needed = self.resolve(parse_requirements(requirements))
##   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
##     raise VersionConflict(dist, req).with_context(dependent_req)
## pkg_resources.ContextualVersionConflict: (scipy 1.4.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scipy<=1.3.3
```
kludgeplate

**Comment by KshitijT** [comment]
Sigh. If possible, please include in the coming release.

**Comment by bennahugo** [comment]
I think this is a singularity bug. I explictly delete that entire folder in dist and it still uses a hash that is out of date. I'm going to mark this as won't fix until the issue is fixed upstream in singularity

**Comment by bennahugo** [comment]
Confirmed it is due to singularity 2.4. The image being built with singularity is not the image built by docker - likely the wrong SHAs are used. With 2.6 the problem goes away

**Comment by KshitijT** [comment]
@viralp reports that this persists even in singularity 2.6, so I am reopening this issue. Also since this is critical to Caracal, adding the tag.

**Comment by bennahugo** [comment]
remove the singularity docker caches and images and repull. Reopen if still a problem
