### ISSUE TITLE
add cab setting to clean up the trash

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela#561]
Motivated by https://github.com/ska-sa/caracal/issues/928, but I see other surplus-to-requirements "artefacts" left over in the output folder: casa files, *.last files, ragavi.log, etc. etc.

I think we need to add an optional entry in ``parameter.json`` called ``cleanup_trash`` or something. This should be a list of glob patterns, any output files matching that pattern are then removed by Stimela.

**Comment by SpheMakh** [comment]
added in #572
