### ISSUE TITLE
make DDFacet and Cubical base image

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/Stimela#573]
@o-smirnov I may need your help on this as I have not installed DDFacet and Cubical on the same system before.

**Comment by SpheMakh** [comment]
@KshitijT I will do some tests but will need you test also.

**Comment by KshitijT** [comment]
Of course. :)

**Comment by bennahugo** [comment]
It's already done Sphe. Please do not modify. I am the only one who
probably understand the complexities of building with full meqtrees,
cubical, fitsbeam ,lofar and ddf support

**Comment by SpheMakh** [comment]
Tabeling this for later, if needed.
