### ISSUE TITLE
update shadems cab

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela#584]
@SpheMakh this is urgently needed so I can get to work on [making inspect_data colourful again](https://github.com/ska-sa/caracal/issues/972). 

I made a release: https://github.com/ratt-ru/shadeMS/releases/tag/v0.3.0

Note though that, for now, datashader needs to be installed from my fork (master): https://github.com/o-smirnov/datashader.

**Comment by Mulan-94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Shadems](https://trello.com/c/mTvFaJT8/41-update-shadems)

**Comment by SpheMakh** [comment]
Fixed
