### ISSUE TITLE
Freeze when pulling singularity automatically during a recipe run

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/Stimela#617]
This happens when the target image already exists, since singularity requires keyboard input. 

```
(tenv) sphe@slwrk-131:~/workdir$ singularity build  IMAGES/stimela_ddfacet_1.3.3.sif docker://stimela/ddfacet:1.3.3
Build target already exists. Do you want to overwrite? [N/y] 
```

**Comment by KshitijT** [comment]
I guess this is a CARACal issue too? Could you please open an issue there as well?

**Comment by SpheMakh** [comment]
All stimela issues are caracal issues, but I don't think there is a need to duplicate all the issues. If someone raises on this caracal just point then here

**Comment by SpheMakh** [comment]
Fixed
