### ISSUE TITLE
CubiCal v1.5.6 Release

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/Stimela#661]
There is a new minor release of CubiCal. This release includes fixes for breakages in the threading layer. 

I don't think there are many changes to the inputs with one exception - `--dist-safe` now takes a `float` instead of an `int`/`bool` and works as a fudge factor. This is for cases where you want to be neighbourly (so using only a percentage of total memory), or where the memory estimates are off (say apply-only mode).

**Comment by Athanaseus** [comment]
closed via #774
