### ISSUE TITLE
Can not provide RR polarization in the wsclean pol option 

### ISSUE THREAD

**Issue by Arnabiitindore** [ratt-ru/Stimela#671]
Can not provide RR polarization in the wsclean. 
I used the recipe as :+1: 
recipe.add("cab/wsclean", "high resolution image", {
     "msname": ms,
     "size":[4096,4096],
     "scale": "1.9asec",
     "mgain": 0.8,
     "multiscale":True,
     "pol":'RR',
     "weighting-rank-filter":3,
     "weighting-rank-filter-size":64,
     "local-rms": True,
     "local-rms-window":15, 
     "auto-mask":3.0,
     "auto-threshold":0.3,
     "weight":'briggs -1',
     "niter": 200000,
     "name": "high_res_robust_minus_1",
     
 }, input=INPUT, output=OUTPUT, label="First image") 

But in wsclean it reads as '-pol' 'R,R' 
Check the screen shot
![RR_prob](https://user-images.githubusercontent.com/20695190/92934318-f6a2e900-f464-11ea-8440-0d4dae8c6442.png)

**Comment by KshitijT** [comment]
@Arnabiitindore , this is a general issue for all polarisation selection apart from I, Q, U V (e.g. the same would happen for XX). 

Probably this line is the culprit:
```
 elif name in 'spws multiscale-scales pol'.split():
        if hasattr(value, '__iter__'):
            value = ','.join(map(str, value))   
```
found here: https://github.com/ratt-ru/Stimela/blob/master/stimela/cargo/cab/wsclean/src/run.py#L49

If you have installed stimela from source, you can try removing 'pol' from the first line as a temporary fix, that should do the job.

**Comment by Arnabiitindore** [comment]
Yes, already done the same and it is running fine now.
