### ISSUE TITLE
Permission denied error when running caracal or stimela script

### ISSUE THREAD

**Issue by Kincaidr** [ratt-ru/Stimela#703]
Hi,

Whenever i run a caracal script using: caracal -c script.yml -sid /home/kincaid/STIMELA_IMAGES -ct singularity or a stimela script using: stimela run script.py i get this permission denied error on both instances:

![image](https://user-images.githubusercontent.com/53697426/111778382-3e477900-88bd-11eb-92e0-46c12fcd01c9.png)

The stimela script is this: 
![image](https://user-images.githubusercontent.com/53697426/111778598-93838a80-88bd-11eb-8739-c9cd61736e72.png)

The caracal script is the usual setup.

Please help thanks!

**Comment by o-smirnov** [comment]
What's the permissions on ``/home/kincaid/STIMELA_IMAGES``? Disk quotas? Neverminds scripts, it falls over at the first hurdle, which is just to download the image...

**Comment by KshitijT** [comment]
Maybe you need to define the stimela pullfolder? 
```
export SINGULARITY_PULLFOLDER=${WORKSPACE_ROOT}/singularity_images

```
from : https://github.com/ratt-ru/Stimela/wiki/Installation

**Comment by Kincaidr** [comment]
> What's the permissions on `/home/kincaid/STIMELA_IMAGES`? Disk quotas? Neverminds scripts, it falls over at the first hurdle, which is just to download the image...

Yes i think i see problem: 
![image](https://user-images.githubusercontent.com/53697426/111786090-16a8de80-88c6-11eb-82b0-8c42f0740d49.png)

The STIMELA_IMAGES folder is owned by my supervisor, but it does have read,write, execute permissions so why would it still be a problem?

**Comment by o-smirnov** [comment]
It's ``rwx`` for Viral, but ``r-x`` for everyone else including you, so not surprising that it can't write. Why don't you have your own images folder?

**Comment by Kincaidr** [comment]
Ok thanks i understand. Im not sure, but i will pull the images myself to create my own folder.

**Comment by o-smirnov** [comment]
Other option is to use ACLs (``chacl``) for Viral to give write-permissions to the folder to you and you only.
