### ISSUE TITLE
SyntaxError: encoding problem: future_fstrings

### ISSUE THREAD

**Issue by Kincaidr** [ratt-ru/Stimela#708]
Hi,
My caracal script is terminating at flag__2 worker, giving: "SyntaxError: encoding problem: future_fstrings."

Here is the output below, logfile is also attached.

![image](https://user-images.githubusercontent.com/53697426/115731381-61b38700-a387-11eb-9aa6-577b96f94e1f.png)

[log-caracal.txt](https://github.com/ratt-ru/Stimela/files/6359071/log-caracal.txt)

Thanks.

**Comment by SpheMakh** [comment]
What version of stimela are you using?

**Comment by Kincaidr** [comment]
stimela version 1.2.5

**Comment by SpheMakh** [comment]
Please update to the latest released version of stimela (1.6.9), and it should work.
