### ISSUE TITLE
Singularity Image file already exists error

### ISSUE THREAD

**Issue by Kincaidr** [ratt-ru/Stimela#718]
Hi,

I get this stimela error when running caracal:

![image](https://user-images.githubusercontent.com/53697426/118113208-4b2ca880-b3e6-11eb-93ea-175cd164ea8c.png)

Thanks for the help!
[log-caracal.txt](https://github.com/ratt-ru/Stimela/files/6471945/log-caracal.txt)

**Comment by o-smirnov** [comment]
@SpheMakh, this part looks the culprit: 
```
# running cd /net/ike/vault-ike/kincaid/A2384_new_data && singularity pull  --name stimela_casa_1.6.3.sif docker://stimela/casa:1.6.3
# FATAL:   Image file already exists: "/net/ike/vault-ike/kincaid/STIMELA_IMAGES/stimela_casa_1.6.3.sif" - will not overwrite
```
It's pulling though the image already exists...

**Comment by KshitijT** [comment]
@Kincaidr , a stopgap measure might be to run caracal as:

` /caracal -c A2384_new_data.yml -ct singularity -sw flag__2 -sid /net/ike/vault-ike/kincaid/STIMELA_IMAGES/`,

that way CARACal won't go looking to download preexisting images.

**Comment by Kincaidr** [comment]
> @Kincaidr , a stopgap measure might be to run caracal as:
> 
> ` /caracal -c A2384_new_data.yml -ct singularity -sw flag__2 -sid /net/ike/vault-ike/kincaid/STIMELA_IMAGES/`,
> 
> that way CARACal won't go looking to download preexisting images.

Thanks! this has worked.
