### ISSUE TITLE
Signals.SIGKILL: 9 on `wsclean`

### ISSUE THREAD

**Issue by bngcebetsha** [ratt-ru/Stimela#737]
Was running `simulation_pipeline.py` and got the following error.

```
Traceback (most recent call last):
  File "/Users/bngcebetsha/Stimela/examples/simulation_pipeline.py", line 118, in <module>
    pipeline.run()
  File "/Users/bngcebetsha/stimela_venv/stimela/lib/python3.9/site-packages/stimela/recipe.py", line 761, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'Imaging MS, robust=2' failed: docker returns error code 1
```
For details please see log file attached.

[log-Simulation_Example-imager_example_robust_0.txt](https://github.com/ratt-ru/Stimela/files/7609578/log-Simulation_Example-imager_example_robust_0.txt)

Please help

**Comment by bennahugo** [comment]
Looks like it was killed by the OOM killer. Try lowering your memory usage. Reopen if needed
