### ISSUE TITLE
Include MosaicQueen 1.0.12 in Stimela please

### ISSUE THREAD

**Issue by paoloserra** [ratt-ru/Stimela#749]
https://github.com/caracal-pipeline/MosaicQueen/releases/tag/1.0.12

Thanks!

**Comment by Athanaseus** [comment]
Is this a separate cab or an updated version of `mosaicstewart`?

**Comment by paoloserra** [comment]
it's meant to replace it

**Comment by Athanaseus** [comment]
Thanks @paoloserra 

Do you by chance have images/files I can use to test this package?
(Also the basic command to run will help)

**Comment by paoloserra** [comment]
Just shared through GDrive

**Comment by paoloserra** [comment]
We're skipping this and going straight to 1.1.1
